### ISSUE TITLE
Add Fedora to test suite

### ISSUE THREAD

**Issue by hectcastro** [basho-labs/riak-chef-cookbook#105]
Vagrant boxes for Fedora 19 and 20 can be found here:

- http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box

**Comment by cheeseplus** [comment]
This was done already but now we've just removed Fedora 19 as it is EOL. There are no packages for Fedora 20 from Basho so this issue is no longer relevant.
