### ISSUE TITLE
Don't use pam_limits for file descriptor limits

### ISSUE THREAD

**Issue by mfischer-zd** [basho-labs/riak-chef-cookbook#120]
The use of pam_limits for Enterprise Linux variants isn't needed.  Explicit `ulimit` declarations should always be made in the startup scripts (or scripts they source, such as `/etc/default/service` or `/etc/sysconfig/service`) for daemons.  pam_limits should be used only for interactive user sessions, which is irrelevant for a service such as Riak.

**Comment by cheeseplus** [comment]
So given that this needs to be fixed upstream (it might already) I am closing this issue out but welcome to re-opening it in the future.
