### ISSUE TITLE
Support for Riak 2.1.1 by default

### ISSUE THREAD

**Issue by mjbrender** [basho-labs/riak-chef-cookbook#167]
Riak 2.1 [is available](https://github.com/basho/riak/releases/tag/riak-2.1.0) and it'd be great to add it to the mix. It also introduces a `write_once` bucket type that may be of interest to implement.

**Comment by mjbrender** [comment]
Hey @basho-labs/chef-committers, what's the best place to start here? I'm glad to help, just want to do so without breaking your processes.

**Comment by cheeseplus** [comment]
@mjbrender I am not getting pinged via e-mail on this one for some reason but I'm looking now.

**Comment by mjbrender** [comment]
Weird @cheeseplus - thanks man!

**Comment by cheeseplus** [comment]
Altered title skipping over 2.1 is for the best.

**Comment by mjbrender** [comment]
:+1:

**Comment by cheeseplus** [comment]
@mjbrender hey can you ping via twitter or e-mail with an updated Enterprise key? I think y'all rolled a new one (which is normal) but now I can't test any of the enterprise stuff.

**Comment by mjbrender** [comment]
Let me figure that out @cheeseplus!

**Comment by cheeseplus** [comment]
Merged 9c33c5924774a82c9efb627f20ba418c20fe5c21
