### ISSUE TITLE
Cookbook dependencies are too tight

### ISSUE THREAD

**Issue by mfischer-zd** [basho-labs/riak-chef-cookbook#168]
The dependencies on cookbooks listed in metadata.rb are more restrictive than necessary, leading to an high risk of unsolvable conflicts with other cookbooks.  The declarations currently listed prevent users from using newer versions of the prerequisite cookbooks, even if the newer cookbooks are still compatible with this one.

Can you please loosen the restrictions to `>=` syntax instead of `~>`?

**Comment by borakou** [comment]
:+1:

**Comment by cheeseplus** [comment]
I don't see why relaxing them would be an issue - out of curiosity which cookbooks are causing issues?

**Comment by mfischer-zd** [comment]
@borakou has data on that.  If you still want to use `~>` syntax, can you use it for 2-component version numbers instead of 3?

OK: `depends "foo", "~> 3.2"` (will work with 3.2 - 3.99.99)
Troublesome: `depends "foo", "~> 1.4.6"` (will work with 1.4.6 - 1.4.99)

**Comment by borakou** [comment]
I am using version 3.1.0 of the riak cookbook.  I think using the >= for those common shared cookbooks, i.e yum, git, sysctl, ulimit, and etc., will greatly reduce the dependency conflict.

https://supermarket.chef.io/cookbooks/riak#dependencies

    "apt": "~> 2.3",
    "build-essential": "~> 2.1.2",
    "erlang": "~> 1.5.2",
    "git": "~> 3.0",
    "java": "~> 1.28.0",
    "sysctl": "~> 0.3.5",
    "ulimit": "~> 0.3.2",
    "yum": "~> 3.4",
    "yum-epel": "~> 0.5.1",
    "packagecloud": ">= 0.0.0",
    "pkg_add": ">= 0.0.0"

**Comment by mjbrender** [comment]
Hey @borakou - I'm still learning how cookbook dependencies play out. Were you able to test that these changes won't break tests? Either you or @mfischer-zd are more than welcome to open PRs to help out (unless you're doing something I don't know about @cheeseplus and this'll break it).

**Comment by cheeseplus** [comment]
This seems fine to me I was just curious which ones specifically were hosing things as this is the first I've heard in quite a while. Many of those we pinned on full semvers x.y.z because of broken stuff but at this point (from experience at least) we should be safe with most of the ones that you suggested.

**Comment by borakou** [comment]
@mjbrender, I use our own cookbook wrapper to call basho riak cookbook.  Currently, we don't use all riak features; I probably wouldn't be able to confirm if it will break anything.  I can try change the OS related cookbooks to >= and test on my wrapper cookbook.  Will report back on the result.

**Comment by ewr** [comment]
In the cookbook versions I have deployed on our chef server, I had to change the apt spec from "~> 2.3.8" to "~> 2.3" (both here and in the riak cs cookbook). Otherwise it was interfering with a libarchive cookbook version that required "~> 2.5". Changing the spec didn't cause any issues in production.

**Comment by cheeseplus** [comment]
If someone could make a PR and run it through test-kitchen I'd much appreciate it - I'm on the road in Australia and Japan for work with a really full schedule so I'm not sure when I'll have time to dedicate on this one (several other things languishing as well) but I can merge something with relative ease.

**Comment by cheeseplus** [comment]
Working on the cookbook now and testing just dropping the deps in metadata.rb - the Chef ecosystem has changed a bunch since these lines with hard(er) deps were added and honestly think we're probably ok dropping these and only tossing anything special in a Berksfile at this point.

**Comment by mjbrender** [comment]
Thanks @cheeseplus! I'd love to see others jump in over the coming releases as needed. It takes a village to raise a repo :+1:

**Comment by cheeseplus** [comment]
Fixed in #177
