### ISSUE TITLE
Riak EE 2.0.8 package fails to install due to new download location

### ISSUE THREAD

**Issue by mikedotson** [basho-labs/riak-chef-cookbook#190]
With the release of Riak EE 2.0.8, the major/minor check [here](https://github.com/basho-labs/riak-chef-cookbook/blob/7e5fffa0025d1ff824353becf511420d3180c332/recipes/package.rb#L29-L34) produces a link including the major_minor string prior to the version string.

However, with Riak EE 2.0.8 and forward, the packages will be available via the standard link location as found on line 31.

Proposing the change of the code to something similar:
```
# Enterprise download URL changed with release of 2.0.8
if Gem::Version.new(version_str) >= Gem::Version.new('2.0.8')
  ee_url_prefix = "http://private.downloads.basho.com/riak_ee/#{node['riak']['package']['enterprise_key']}/#{version_str}"
else
  ee_url_prefix = "http://private.downloads.basho.com/riak_ee/#{node['riak']['package']['enterprise_key']}/#{major_minor}/#{version_str}"
end
```

**Comment by cheeseplus** [comment]
I doubt Basho is going to provide me updated keys for testing at this juncture but if they do or you'd like to make a PR I'd give it a look.

**Comment by mikedotson** [comment]
I've created a pull request with the proposed code changes and looks like it's failing the Travis CI integration tests.  Not sure if Chef will need additional code changes to use Gem::Version or not.  If it does, let me know and I can make additional changes as needed.

Thanks!

**Comment by mikedotson** [comment]
The download locations for the Debian packages have also changed with versions 2.2.0 and greater and between versions 2.0.8 and 2.1.0.

Link locations changed from using the platform version number to using the code name as is done with the Ubuntu packages.
